name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Verify:
    runs-on: ubuntu-latest

    steps:
      - name: Download Nginx
        run: |
          sudo systemctl start nginx
          sudo systemctl status nginx

      - name: Download Config
        run: |
          cd /etc/nginx/
          git init
          git remote add origin https://github.com/StepBroBD/Template-Nginx.git
          git fetch --all
          git reset --hard origin/master
          git pull origin master

      - name: Verify Config
        run: |
          make verify
