name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Verify:
    runs-on: ubuntu-latest

    steps:
      - name: Download Nginx
        run: |
          sudo systemctl start nginx
          sudo systemctl status nginx

      - name: Download Config
        run: |
          git clone https://github.com/StepBroBD/Template-Nginx.git

      - name: Verify Config
        run: |
          make verify
