name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Verify:
    runs-on: ubuntu-latest

    steps:
      - name: Download Nginx
        run: |
          sudo systemctl start nginx
          sudo systemctl status nginx

      - name: Download Config
        run: |
          cd /etc/nginx/
          sudo git init
          sudo git remote add origin https://github.com/StepBroBD/Template-Nginx.git
          sudo git fetch --all
          sudo git reset --hard origin/master
          sudo git pull origin master

      - name: Verify Config
        run: |
          make verify
